### PR TITLE
Some documentation

### PR DESCRIPTION
**Pull request by dakkar**
Hello!
I noticed that many piece of BB lack any kind of detailed documentation, so I wrote some.
I still need to write something for containers, but I thought I'd see if the level / tone / style of what I have already written is something that you'd consider using. Also, if you have any suggestion or correction, please let me know.

### CODE REVIEW

**Comment by yanick** [comment]
Awesome! 8-D  I'll have a read tonight, and will get back to you.

**Comment by yanick** [comment]
I've (very quickly) read through the additions, and they look pretty fantastic.

@stevan You might want to chime in before I open the gates and take all that goodness in, but that documentation patch seems to be all we could wish for.

**Comment by stevan** [comment]
A quick skim of these look good to me as well. I am not sure I will have time for a more thorough review, so I will defer to @yanick.

**Comment by yanick** [comment]
Beautiful. Thanks @stevan!  Just wanted to make sure that you are at least remotely aware of what's going on, and not utterly appalled by it. ^.^

**Comment by dakkar** [comment]
Another thing I might do: normalise the style of all method/attribute headings, using more of Pod::Weaver.

**Comment by dakkar** [comment]
Oh, another thing: this work has been done on company time (I work for net-a-porter, see @NET-A-PORTER ); what would be a sensible way to express this in the documentation?

**Comment by stevan** [comment]
@dakkar I have no issue with giving Net-A-Porter credit where credit is due, you can add it to the Changes file and put something in the POD if you like (documentation credit or something, up to you really).

**Comment by dakkar** [comment]
I consider this work "done" now, you can merge it if you like.

**Comment by yanick** [comment]
Sweet. @dakkar++ 
I'll begin the mega-merge as soon as I can.

**Comment by yanick** [comment]
Merged! Will be published soonishly! Thanks again. :-)

**Pull request merged**
