### PR TITLE
add keyword 'literal'

### LINKED ISSUE #31: Add an equivalent to dep(value => ...) to Bread::Board
I'm not a fan of Bread::Board::Declare, but I've often found myself wanting something like `dep(value => ...)` when using Bread::Board. It would be nice to be able to quickly specify anonymous literals to service dependencies. 

Would it be possible to add a `literal()` or `value()` function to Bread::Board to create anonymous Bread::Board::Literal services?

### PR DESCRIPTION
**Pull request by yanick**
Fixes #31

### CODE REVIEW

**Comment by stevan** [comment]
I could have sworn we had this in the past, my memory must be getting worse (or was it better, I don't recall)

**Comment by yanick** [comment]
Yup. Phantom patches. I wish I could say that didn't happen to me too. :-)

**Comment by doy** [comment]
OX has it, which is probably what you're thinking of

**Comment by stevan** [comment]
@yanick do you need a release? also, want co-maint?

**Comment by yanick** [comment]
No urgent need of release. I'm just learning about the tool by messing with it, as usual. :-)

As for co-maint, sure, I never turn down additional powers. ^.^

**Comment by stevan** [comment]
You .... have .... CO MAINT!!!!

**Comment by yanick** [comment]
I am now officially mad with the power. O____o

Thanks!

**Pull request merged**
